spring:
  profiles:
    active: dev

zagent:
  mcp:
    sync:
      enabled: true
      manifest:
        models:
          - modelId: "2002"
            apiId: "1001"
            modelName: "gpt-5.4"
            modelType: "openai"
            status: 1
          - modelId: "2005"
            apiId: "1001"
            modelName: "gpt-5.4"
            modelType: "openai"
            status: 1
          - modelId: "2006"
            apiId: "1001"
            modelName: "gpt-5.4"
            modelType: "openai"
            status: 1
        mcps:
          - mcpId: "5001"
            mcpName: "filesystem-docs"
            transportType: "stdio"
            transportConfig: '{"filesystem":{"command":"${zagent.mcp.filesystem.command:cmd.exe}","args":["/c","npx","-y","@modelcontextprotocol/server-filesystem","${zagent.mcp.filesystem.docs-path:D:/dev/my_proj/zagent/docs}"],"env":{"MCP_LOG_LEVEL":"info"}}}'
            requestTimeout: 10
            status: 1
          - mcpId: "5003"
            mcpName: "amap-sse"
            transportType: "sse"
            transportConfig: '{"baseUri":"${zagent.mcp.amap.base-uri:http://127.0.0.1:18081}","sseEndpoint":"${zagent.mcp.amap.sse-endpoint:/sse}"}'
            requestTimeout: 20
            status: 1
          - mcpId: "5004"
            mcpName: "git-repo"
            transportType: "sse"
            transportConfig: '{"baseUri":"${zagent.mcp.git-repo.base-uri:http://127.0.0.1:18082}","sseEndpoint":"${zagent.mcp.git-repo.sse-endpoint:/sse}"}'
            requestTimeout: 10
            status: 1
        bindings:
          - sourceType: "model"
            sourceId: "2002"
            targetType: "tool_mcp"
            targetIds:
              - "5001"
            status: 1
          - sourceType: "model"
            sourceId: "2005"
            targetType: "tool_mcp"
            targetIds:
              - "5003"
            status: 1
          - sourceType: "model"
            sourceId: "2006"
            targetType: "tool_mcp"
            targetIds:
              - "5004"
            status: 1
          - sourceType: "client"
            sourceId: "3006"
            targetType: "model"
            targetIds:
              - "2005"
            status: 1
          - sourceType: "client"
            sourceId: "3008"
            targetType: "model"
            targetIds:
              - "2005"
            status: 1
